### ISSUE TITLE
Crash: java.lang.IllegalStateException: Expected the adapter to be 'fresh' while restoring state.

### ISSUE THREAD

**Issue by gabrielbull** [callstack/react-native-viewpager#183]
# Bug report

## Summary

When navigating using android native fragments, restoring a screen with a ViewPager crashes on android. This is a regression in version 4 that did not happen in version 3.

Here is the complete crash stack trace:

```
FATAL EXCEPTION: main
Process: com.sealjobsemployee.staging, PID: 24614
java.lang.IllegalStateException: Expected the adapter to be 'fresh' while restoring state.
at com.reactnative.community.viewpager2.adapter.FragmentStateAdapter.restoreState(FragmentStateAdapter.java:537)
at com.reactnative.community.viewpager2.widget.ViewPager2.restorePendingState(ViewPager2.java:352)
at com.reactnative.community.viewpager2.widget.ViewPager2.dispatchRestoreInstanceState(ViewPager2.java:377)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4699)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4699)
at android.view.View.restoreHierarchyState(View.java:21555)
at androidx.fragment.app.Fragment.restoreViewState(Fragment.java:573)
at androidx.fragment.app.FragmentStateManager.restoreViewState(FragmentStateManager.java:356)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1189)
at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:2224)
at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1997)
at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1953)
at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:237)
at android.app.ActivityThread.main(ActivityThread.java:8016)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
```

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 10.15.5
    CPU: (16) x64 Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz
    Memory: 927.14 MB / 64.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.4.0 - ~/.nvm/versions/node/v14.4.0/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v14.4.0/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v14.4.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /Users/gabriel/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_222 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 4.0.1

## Steps to reproduce

Restore view state on android

## Reproducible sample code

n/a

**Comment by troZee** [comment]
`When navigating using android native fragments, restoring a screen with a ViewPager crashes on android. `

Could you provide a code snippet ? I would like to test below solutions: 
https://stackoverflow.com/questions/56646711/expected-the-adapter-to-be-fresh-while-restoring-state

**Comment by gabrielbull** [comment]
Here is a code snippet to reproduce the bug.

You need to install `navigation`, `navigation-react` and `navigation-react-native`.

```shell
npx react-native init ViewPagerDemo
cd ViewPagerDemo
yarn add navigation navigation-react navigation-react-native
```

Replace `App.js` with this:

```jsx
import React, {useMemo, useContext, useCallback} from 'react';
import {StyleSheet, View} from 'react-native';
import ViewPager from '@react-native-community/viewpager';
import {Button} from './Button';
import {StateNavigator} from 'navigation';
import {NavigationHandler, NavigationContext} from 'navigation-react';
import {NavigationStack} from 'navigation-react-native';

export const Button = ({children, onPress}) => {
  return (
    <TouchableNativeFeedback onPress={onPress}>
      <View style={styles.container}>
        <Text style={styles.label}>{children}</Text>
      </View>
    </TouchableNativeFeedback>
  );
};

const Screen1 = () => {
  const {stateNavigator} = useContext(NavigationContext);
  const onPress = useCallback(() => {
    stateNavigator.navigate('screen2');
  }, [stateNavigator]);
  return (
    <ViewPager style={styles.viewPager} initialPage={0}>
      <View key="1" style={styles.page1}>
        <Button onPress={onPress}>Go to next screen</Button>
      </View>
      <View key="2" style={styles.page2} />
    </ViewPager>
  );
};

const Screen2 = () => {
  const {stateNavigator} = useContext(NavigationContext);
  const onPress = useCallback(() => {
    stateNavigator.navigateBack(1);
  }, [stateNavigator]);
  return (
    <View style={styles.screen2}>
      <Button onPress={onPress}>Go back</Button>
    </View>
  );
};

const App = () => {
  const stateNavigator = useMemo(() => {
    var stateNavigator = new StateNavigator([
      {key: 'screen1'},
      {key: 'screen2', trackCrumbTrail: true},
    ]);
    stateNavigator.states.screen1.renderScene = () => <Screen1 />;
    stateNavigator.states.screen2.renderScene = () => <Screen2 />;
    stateNavigator.navigate('screen1');
    return stateNavigator;
  }, []);

  return (
    <NavigationHandler stateNavigator={stateNavigator}>
      <NavigationStack />
    </NavigationHandler>
  );
};

const styles = StyleSheet.create({
  container: {
    padding: 8,
    backgroundColor: 'blue',
    elevation: 2,
    borderRadius: 4,
  },
  label: {
    color: 'white',
  },
  viewPager: {
    flex: 1,
  },
  page1: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'red',
  },
  page2: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'green',
  },
  screen2: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
});

export default App;
```

**Comment by dharminderraja** [comment]
same issue here .. was not happening in the prior version

**Comment by Rolstenhouse** [comment]
Same issue here. Just received a crash report from a user

```java.lang.IllegalStateException: 
  at com.reactnative.community.viewpager2.adapter.FragmentStateAdapter.restoreState (FragmentStateAdapter.java:21)
  at d.h.a.a.b.f.i (ViewPager2.java:5)
  at d.h.a.a.b.f.dispatchRestoreInstanceState (ViewPager2.java:8)
  at android.view.ViewGroup.dispatchRestoreInstanceState (ViewGroup.java:4045)
  at android.view.View.restoreHierarchyState (View.java:20257)
  at androidx.fragment.app.Fragment.restoreViewState (Fragment.java:2)
  at androidx.fragment.app.r.l (FragmentStateManager.java:4)
  at androidx.fragment.app.l.D0 (FragmentManager.java:27)
  at androidx.fragment.app.l.C0 (FragmentManager.java:1)
  at androidx.fragment.app.l.A0 (FragmentManager.java:4)
  at androidx.fragment.app.a.D (BackStackRecord.java:26)
  at androidx.fragment.app.l.T (FragmentManager.java:6)
  at androidx.fragment.app.l.U (FragmentManager.java:14)
  at androidx.fragment.app.l.R0 (FragmentManager.java:10)
  at androidx.fragment.app.l.S (FragmentManager.java:5)
  at androidx.fragment.app.a.k (BackStackRecord.java:2)
  at com.reactnative.community.viewpager2.adapter.FragmentStateAdapter.placeFragmentInViewHolder (FragmentStateAdapter.java:18)
  at com.reactnative.community.viewpager2.adapter.FragmentStateAdapter.onViewAttachedToWindow (FragmentStateAdapter.java:2)
  at com.reactnative.community.viewpager2.adapter.FragmentStateAdapter.onViewAttachedToWindow (FragmentStateAdapter.java:1)
  at androidx.recyclerview.widget.RecyclerView.dispatchChildAttached (RecyclerView.java:4)
  at androidx.recyclerview.widget.RecyclerView$e.g (RecyclerView.java:2)
  at androidx.recyclerview.widget.b.a (ChildHelper.java:5)
  at androidx.recyclerview.widget.RecyclerView$o.addViewInt (RecyclerView.java:13)
  at androidx.recyclerview.widget.RecyclerView$o.addView (RecyclerView.java:2)
  at androidx.recyclerview.widget.RecyclerView$o.addView (RecyclerView.java:1)
  at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk (LinearLayoutManager.java:6)
  at androidx.recyclerview.widget.LinearLayoutManager.fill (LinearLayoutManager.java:9)
  at androidx.recyclerview.widget.LinearLayoutManager.scrollBy (LinearLayoutManager.java:7)
  at androidx.recyclerview.widget.LinearLayoutManager.scrollVerticallyBy (LinearLayoutManager.java:2)
  at androidx.recyclerview.widget.RecyclerView.scrollStep (RecyclerView.java:6)
  at androidx.recyclerview.widget.RecyclerView.scrollByInternal (RecyclerView.java:5)
  at androidx.recyclerview.widget.RecyclerView.onTouchEvent (RecyclerView.java:42)
  at d.h.a.a.b.f$m.onTouchEvent (ViewPager2.java:1)
  at android.view.View.dispatchTouchEvent (View.java:13488)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3216)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2888)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3222)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2904)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3222)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2904)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3222)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2904)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3222)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2904)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3222)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2904)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3222)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2904)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3222)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2904)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3222)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2904)
  at versioned.host.exp.exponent.modules.api.components.gesturehandler.react.RNGestureHandlerEnabledRootView.dispatchTouchEvent (RNGestureHandlerEnabledRootView.java:2)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3222)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2904)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3222)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2904)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3222)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2904)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3222)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2904)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3222)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2904)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3222)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2904)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3222)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2904)
  at com.android.internal.policy.DecorView.superDispatchTouchEvent (DecorView.java:697)
  at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent (PhoneWindow.java:1879)
  at android.app.Activity.dispatchTouchEvent (Activity.java:3487)
  at b.a.o.i.dispatchTouchEvent (WindowCallbackWrapper.java:1)
  at com.android.internal.policy.DecorView.dispatchTouchEvent (DecorView.java:655)
  at android.view.View.dispatchPointerEvent (View.java:13736)
  at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent (ViewRootImpl.java:6119)
  at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess (ViewRootImpl.java:5897)
  at android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:5346)
  at android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:5399)
  at android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:5365)
  at android.view.ViewRootImpl$AsyncInputStage.forward (ViewRootImpl.java:5524)
  at android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:5373)
  at android.view.ViewRootImpl$AsyncInputStage.apply (ViewRootImpl.java:5581)
  at android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:5346)
  at android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:5399)
  at android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:5365)
  at android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:5373)
  at android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:5346)
  at android.view.ViewRootImpl.deliverInputEvent (ViewRootImpl.java:8408)
  at android.view.ViewRootImpl.doProcessInputEvents (ViewRootImpl.java:8341)
  at android.view.ViewRootImpl.enqueueInputEvent (ViewRootImpl.java:8294)
  at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent (ViewRootImpl.java:8523)
  at android.view.InputEventReceiver.dispatchInputEvent (InputEventReceiver.java:198)
  at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents (Native Method)
  at android.view.InputEventReceiver.consumeBatchedInputEvents (InputEventReceiver.java:187)
  at android.view.ViewRootImpl.doConsumeBatchedInput (ViewRootImpl.java:8482)
  at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run (ViewRootImpl.java:8550)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:986)
  at android.view.Choreographer.doCallbacks (Choreographer.java:764)
  at android.view.Choreographer.doFrame (Choreographer.java:693)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:965)
  at android.os.Handler.handleCallback (Handler.java:873)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7073)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:494)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:964)```

**Comment by Bang9** [comment]
+1

**Comment by troZee** [comment]
@gabrielbull could you test it ?

**Comment by gabrielbull** [comment]
lgtm
